<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.3.10</Version>
    <ReleaseDate>2026-09-23</ReleaseDate>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../DeskMonitor.Core/DeskMonitor.Core.csproj" /></ItemGroup>
  <ItemGroup><AssemblyMetadata Include="ReleaseDate" Value="$(ReleaseDate)" /></ItemGroup>
  <ItemGroup><RuntimeHostConfigurationOption Include="System.GC.ConserveMemory" Value="9" /></ItemGroup>
</Project>
